// Code generated by Kitex v0.12.3. DO NOT EDIT.
package relationhandler

import (
	server "github.com/cloudwego/kitex/server"
	"github.com/qingyggg/aufer/biz/model/cmd/relation"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler relation.RelationHandler, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler relation.RelationHandler, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
