// Code generated by Kitex v0.12.3. DO NOT EDIT.
package commenthandler

import (
	server "github.com/cloudwego/kitex/server"
	comment "github.com/qingyggg/aufer/kitex_gen/cmd/comment"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler comment.CommentHandler, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler comment.CommentHandler, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
