// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	article "github.com/qingyggg/aufer/biz/router/article"
	comment "github.com/qingyggg/aufer/biz/router/comment"
	relation "github.com/qingyggg/aufer/biz/router/relation"
	user "github.com/qingyggg/aufer/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	comment.Register(r)

	relation.Register(r)

	article.Register(r)

	user.Register(r)

}
